### PR TITLE
Class property semi colons, more lint fixes

### PR DESCRIPTION
**Pull request by zebapy**
Some more lint fixes and added semi colons for all class properties I got errors for. 

I meant to sync this to the branch before you merged but you beat me to it :)

### CODE REVIEW

**Comment by Dindaleon** [comment]
- I am running on Windows and it complains if I don't have the `SET` command and spaces before ampernsands. It would be nice to have a nodejs module that removes the need for that, similar to what rimraf does.
- Can you tell me what is the lint rule that requires semi colons for classes so I can add it.
- I requested a new rule for jsx curly braces so that we can have `{{ }}` instead of `{ { } }` https://github.com/yannickcr/eslint-plugin-react/issues/388
- That bind was needed. Thanks. I am not using parentheses on single parameter arrow functions though. So if you see functions with single parameters that have parentheses, please remove them.

**Comment by zebapy** [comment]
- could perhaps check out something like cross-env for handling this https://github.com/gaearon/react-transform-boilerplate/blob/master/package.json#L7 does it.
- I wasn't getting a lint rule error about it. Babel was simply not compiling because of new semi-colon rule for property specs https://github.com/babel/babel/pull/3225
- Interesting. Another reason to just use spaceless ;) 
- Are you sure? I just moved the bind to the method. it should still work (granted I can revert to no parens around the arg) https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md#no-bind-or-arrow-functions-in-jsx-props

**Comment by Dindaleon** [comment]
- I will check it out.
- Good! I will look around if there is lint rule for this.
- ;)
- I do not understand your last point. Am I sure about what?

**Comment by zebapy** [comment]
Sorry, are you sure you needed the bind created in that manner? `::` vs fat arrows in the actual method. The bind is not removed. Simply the manner of how it is done is changed. I can revert it if you're interested in merging the rest of this, else just close it. Honestly this is the most I've publicly contributed on GitHub. I felt inspired to do a few things on this since I've switched my react app to use Hapi as a server since my API was already built in it, and this is the repo I found as an example.

**Comment by Dindaleon** [comment]
There was a misunderstanding. When I said "That bind was needed" I meant that your modification was the right way of doing it. Sorry.

I hope you continue your contribution :)

**Comment by flying-sheep** [comment]
[6.5.2](https://github.com/babel/babel/releases/tag/v6.5.2) has the semicolon thing reverted!

**Comment by Dindaleon** [comment]
Thank you for letting us know.

**Pull request merged**
