### PR TITLE
Upgrade dev dependancies (migration to babel 6)

### PR DESCRIPTION
**Pull request by AdrieanKhisbe**
Configure babel 6

### CODE REVIEW

**Comment by nelix** [comment]
You would also need to upgrade babel-plugin-react-transform to the 2.\* beta for it to work with babel6

**Comment by AdrieanKhisbe** [comment]
you sure?

cf : https://github.com/gaearon/babel-plugin-react-transform
1.1.1 has been release 7 days ago

and quoting readme :

> :rocket: Now with Babel 6 support (thank you @thejameskyle!)

**Comment by jamiebuilds** [comment]
1.x is for Babel 5, 2.x is for Babel 6. I'll be releasing 2.x whenever I get to it.

**Comment by AdrieanKhisbe** [comment]
indeed: the bold and logo attracted my attention too much ^^.
@thejameskyle Ping me when it's done, I'll update the dependancies then :)

**Comment by jamiebuilds** [comment]
>  Ping me when it's done, I'll update the dependancies then :)

@AdrieanKhisbe Don't hold your breath on that. The only reason I'm in this issue is because you pinged me.

**Comment by AdrieanKhisbe** [comment]
@thejameskyle haha, I was just registering a callback. ;) #asyncStyle

(and sorry having you bring here, I always forgot that the `@some-name` in quote are also warned. :/)

**Comment by nelix** [comment]
@AdrieanKhisbe there is a 2.\* beta, I been using it... its mostly OK except it sometimes thinks class myClass is a react component if it has a render function (rather than being inherited from React.Component)

**Comment by jamiebuilds** [comment]
@nelix have you had trouble with that?

**Comment by Dindaleon** [comment]
Hi @AdrieanKhisbe, Do we need the `.babelrc` file for the new version? I ask you this because the settings for babel are inside the webpack files as I was having some trouble setting it up together with `react-transform`

**Comment by AdrieanKhisbe** [comment]
Hey @Dindaleon.
I have to admit I'm still not familiar of webpack.
It seems that webpack know about `.babelrc` and will get its babel config from there: 
cf 

> Hint: .babelrc
> Note that you could omit the presets option passed to Webpack’s query, and instead add a .babelrc file:
> 
>    {
>        "presets": ["es2015", "react"]
>      }

(some links I end up on: http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/, http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/)

**Pull request merged**
